### ISSUE TITLE
Can't override injectGlobal fonts

### ISSUE THREAD

**Issue by numbofathma** [Pykmi/react-skeleton-ui#14]
I don't want to use the raleway default font and I'm keep geting:
http://localhost:3000/fonts/raleway-v12-latin-regular.woff net::ERR_ABORTED 404 (Not Found)

Any ideas?

**Comment by Pykmi** [comment]
Sounds like you have not copied the fonts into your project, so your app cannot find them. Try copying the fonts/ folder from react-skeleton-ui into your React project's public/ folder.

That should get the Raleway fonts to work.

To use another font, you need to: get the webfonts from places like google fonts, copy them similarly to your public/ folder and change the font-face directives in /src/index.js.

You should find them under the injectGlobal function; a long list of @font-face directives. I tend to use [google-webfonts-helper](https://google-webfonts-helper.herokuapp.com/fonts), which makes things a lot easier; you can select the font you want, the app gives you code to copy and fonts to download. It even lets you specific what font sizes you want.

Hope that helps.
